server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oh_coupon
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root: info

